// app/tra-cuu-diem-chuan/university-data.ts

export interface University {
  code: string;
  name: string;
}

export const universityList: University[] = [
    { code: "KHA", name: "Đại Học Kinh Tế Quốc Dân" },
    { code: "BKA", name: "Đại Học Bách Khoa Hà Nội" },
    { code: "HTC", name: "Học Viện Tài chính" },
    { code: "NHH", name: "Học Viện Ngân Hàng" },
    { code: "NTH", name: "Trường Đại học Ngoại thương" },
    { code: "QSB", name: "Trường Đại Học Bách Khoa HCM" },
    { code: "YHB", name: "Trường Đại Học Y Hà Nội" },
    { code: "BVH", name: "Học Viện Công Nghệ Bưu Chính Viễn Thông" },
    { code: "SPH", name: "Trường Đại Học Sư Phạm Hà Nội" },
    { code: "TMU", name: "Trường Đại Học Thương Mại" },
    { code: "SPS", name: "Trường Đại Học Sư Phạm TPHCM" },
    { code: "YDS", name: "Đại Học Y Dược TPHCM" },
    { code: "QHI", name: "Trường Đại Học Công Nghệ – Đại Học Quốc Gia Hà Nội" },
    { code: "HNM", name: "Trường Đại học Thủ Đô Hà Nội" },
    { code: "GHA", name: "Trường Đại Học Giao Thông Vận Tải" },
    { code: "YTB", name: "Trường Đại Học Y Dược Thái Bình" },
    { code: "KMA", name: "Học Viện Kỹ Thuật Mật Mã" },
    { code: "DCN", name: "Trường Đại Học Công Nghiệp Hà Nội" },
    { code: "YPB", name: "Trường Đại Học Y Dược Hải Phòng" },
    { code: "IUH", name: "Trường Đại Học Công Nghiệp TPHCM" },
    { code: "HPN", name: "Học Viện Phụ Nữ Việt Nam" },
    { code: "DKH", name: "Trường Đại Học Dược Hà Nội" },
    { code: "ANH", name: "Học Viện An Ninh Nhân Dân" },
    { code: "DKY", name: "Trường Đại Học Kỹ Thuật Y Tế Hải Dương" },
    { code: "GTS", name: "Trường Đại Học Giao Thông Vận Tải TPHCM" },
    { code: "HYD", name: "Học Viện Y Dược Học Cổ Truyền Việt Nam" },
    { code: "CSH", name: "Học Viện Cảnh Sát Nhân Dân" },
    { code: "DKK", name: "Trường Đại Học Kinh Tế Kỹ Thuật Công Nghiệp" },
    { code: "DCT", name: "Trường Đại Học Công Thương TPHCM" },
    { code: "LAH", name: "Trường Sĩ Quan Lục Quân 1 - Đại học Trần Quốc Tuấn" },
    { code: "HQH", name: "Học Viện Hải Quân" },
    { code: "HHK", name: "Học Viện Hàng không Việt Nam" },
    { code: "PKA", name: "Trường Đại Học Phenikaa" },
    { code: "PKH", name: "Học Viện Phòng Không – Không Quân" },
    { code: "CSS", name: "Trường Đại Học Cảnh Sát Nhân Dân" },
    { code: "TTH", name: "Trường Sĩ Quan Thông Tin - Hệ Quân sự - Đại Học Thông Tin Liên Lạc" },
    { code: "NHF", name: "Trường Đại Học Hà Nội" },
    { code: "KQH", name: "Học Viện Kỹ Thuật Quân Sự - Hệ Quân sự" },
    { code: "YTC", name: "Trường Đại Học Y Tế Công Cộng" },
    { code: "HQT", name: "Học Viện Ngoại Giao" },
    { code: "ANS", name: "Trường Đại Học An Ninh Nhân Dân" },
    { code: "YCT", name: "Trường Đại Học Y Dược Cần Thơ" },
    { code: "TDM", name: "Trường Đại học Thủ Dầu Một" },
    { code: "TYS", name: "Trường Đại Học Y Khoa Phạm Ngọc Thạch" },
    { code: "DTL", name: "Trường Đại Học Thăng Long" },
    { code: "TLA", name: "Trường Đại Học Thủy Lợi" },
    { code: "QST", name: "Trường Đại Học Khoa Học Tự Nhiên TPHCM" },
    { code: "VHH", name: "Trường Đại Học Văn Hóa Hà Nội" },
    { code: "DTT", name: "Trường Đại Học Tôn Đức Thắng" },
    { code: "HVN", name: "Học Viện Nông Nghiệp Việt Nam" },
    { code: "QHX", name: "Trường Đại Học Khoa Học Xã Hội và Nhân Văn Hà Nội" },
    { code: "LPH", name: "Trường Đại Học Luật Hà Nội" },
    { code: "QHF", name: "Trường Đại Học Ngoại Ngữ - ĐH Quốc gia Hà Nội" },
    { code: "HBT", name: "Học viện Báo chí và Tuyên truyền" },
    { code: "QHT", name: "Trường Đại Học Khoa Học Tự Nhiên Hà Nội" },
    { code: "QHE", name: "Trường Đại Học Kinh Tế - ĐHQG Hà Nội" },
    { code: "QSX", name: "Trường Đại Học Khoa Học Xã Hội và Nhân Văn TPHCM" },
    { code: "DTS", name: "Đại Học Sư Phạm Thái Nguyên" },
    { code: "LCH", name: "Trường Sĩ Quan Chính Trị - Đại Học Chính Trị" },
    { code: "TCT", name: "Trường Đại Học Cần Thơ" },
    { code: "DKS", name: "Trường Đại học Kiểm Sát Hà Nội" },
    { code: "BPH", name: "Học Viện Biên Phòng" },
    { code: "QHL", name: "Trường Đại học Luật – ĐHQG Hà Nội" },
    { code: "DHS", name: "Trường Đại Học Sư Phạm Huế" },
    { code: "QSC", name: "Trường Đại Học Công Nghệ Thông Tin - ĐHQG TPHCM" },
    { code: "SGD", name: "Trường Đại Học Sài Gòn" },
    { code: "NQH", name: "Học Viện Khoa Học Quân Sự - Hệ Quân sự" },
    { code: "NTS", name: "Trường Đại học Ngoại thương (Cơ sở II)" },
    { code: "HTA", name: "Học viện Tòa án" },
    { code: "DDS", name: "Trường Đại Học Sư Phạm - Đại Học Đà Nẵng" },
    { code: "SP2", name: "Trường Đại Học Sư Phạm Hà Nội 2" },
    { code: "QHS", name: "Trường Đại Học Giáo Dục - ĐHQG Hà Nội" },
    { code: "VHS", name: "Trường Đại Học Văn Hóa TPHCM" },
    { code: "SPK", name: "Trường Đại Học Sư Phạm Kỹ Thuật TPHCM" },
    { code: "HTN", name: "Học Viện Thanh Thiếu Niên Việt Nam" },
    { code: "YQH", name: "Học Viện Quân Y - Hệ Quân sự" },
    { code: "QSK", name: "Trường Đại học Kinh Tế Luật TPHCM" },
    { code: "HEH", name: "Học Viện Hậu Cần - Hệ Quân sự" },
    { code: "LPS", name: "Trường Đại Học Luật TPHCM" },
    { code: "DDF", name: "Trường Đại Học Ngoại Ngữ Đà Nẵng" },
    { code: "KSA", name: "Đại Học Kinh Tế TPHCM" },
    { code: "QHY", name: "Trường Đại học Y Dược - ĐHQG Hà Nội" },
    { code: "DDK", name: "Trường Đại Học Bách Khoa Đà Nẵng" },
    { code: "DHF", name: "Trường Đại Học Ngoại Ngữ Huế" },
    { code: "DMS", name: "Trường Đại Học Tài Chính Marketing" },
    { code: "GSA", name: "Trường Đại Học Giao Thông Vận Tải (Cơ sở 2)" },
    { code: "TSN", name: "Trường Đại Học Nha Trang" },
    { code: "LBH", name: "Trường Sĩ Quan Lục Quân 2 - Đại học Nguyễn Huệ" },
    { code: "BVS", name: "Học Viện Công Nghệ Bưu Chính Viễn Thông (Cơ sở TP.HCM)" },
    { code: "YKV", name: "Trường Đại Học Y Khoa Vinh" },
    { code: "YDN", name: "Trường Đại học Kỹ thuật Y Dược Đà Nẵng" },
    { code: "DTY", name: "Trường Đại Học Y Dược Thái Nguyên" },
    { code: "DHY", name: "Trường Đại Học Y Dược Huế" },
    { code: "DDY", name: "Trường Y Dược Đà Nẵng" },
    { code: "KTS", name: "Trường Đại Học Kiến Trúc TPHCM" },
    { code: "HCA", name: "Học Viện Chính Trị Công An Nhân Dân" },
    { code: "QSY", name: "Trường Đại học Khoa học sức khỏe TPHCM" },
    { code: "QSQ", name: "Trường Đại Học Quốc Tế - ĐHQG TPHCM" },
    { code: "THV", name: "Trường Đại Học Hùng Vương" },
    { code: "THP", name: "Trường Đại Học Hải Phòng" },
    { code: "HCP", name: "Học Viện Chính Sách và Phát Triển" },
    { code: "MHN", name: "Trường Đại Học Mở Hà Nội" },
    { code: "LDA", name: "Trường Đại Học Công Đoàn" },
    { code: "HHA", name: "Trường Đại Học Hàng Hải Việt Nam" },
    { code: "KTA", name: "Trường Đại Học Kiến Trúc Hà Nội" },
    { code: "TDV", name: "Trường Đại Học Vinh" },
    { code: "QSA", name: "Trường Đại Học An Giang" },
    { code: "HCH", name: "Học Viện Hành Chính và Quản trị công" },
    { code: "SPD", name: "Trường Đại Học Đồng Tháp" },
    { code: "QHK", name: "Trường Khoa học liên ngành và Nghệ thuật Hà Nội" },
    { code: "TTN", name: "Trường Đại Học Tây Nguyên" },
    { code: "DQN", name: "Trường Đại Học Quy Nhơn" },
    { code: "DHC", name: "Khoa Giáo Dục Thể Chất Huế" },
    { code: "GNT", name: "Trường Đại Học Sư Phạm Nghệ Thuật Trung Ương" },
    { code: "DDQ", name: "Trường Đại Học Kinh Tế – Đại Học Đà Nẵng" },
    { code: "VKU", name: "Trường Đại học Công nghệ Thông tin và Truyền thông Việt Hàn - Đại học Đà Nẵng" },
    { code: "DTF", name: "Trường Ngoại Ngữ Thái Nguyên" },
    { code: "HLU", name: "Trường Đại Học Hạ Long" },
    { code: "DKT", name: "Trường Đại Học Hải Dương" },
    { code: "DQB", name: "Trường Đại Học Quảng Bình" },
    { code: "DPQ", name: "Trường Đại Học Phạm Văn Đồng" },
    { code: "HHT", name: "Trường Đại Học Hà Tĩnh" },
    { code: "DMT", name: "Trường Đại học Tài Nguyên và Môi Trường Hà Nội" },
    { code: "HCS", name: "Học Viện Hành Chính Và Quản Trị Công (phía Nam)" },
    { code: "NHS", name: "Trường Đại Học Ngân Hàng TPHCM" },
    { code: "DLX", name: "Trường Đại Học Lao Động – Xã Hội" },
    { code: "DBL", name: "Trường Đại Học Bạc Liêu" },
    { code: "DQU", name: "Trường Đại Học Quảng Nam" },
    { code: "DLS", name: "Trường Đại Học Lao Động – Xã Hội (Cơ sở II)" },
    { code: "DPY", name: "Trường Đại Học Phú Yên" },
    { code: "DDP", name: "Phân Hiệu Đại Học Đà Nẵng tại Kon Tum" },
    { code: "TDH", name: "Trường Đại Học Sư Phạm Thể Dục Thể Thao Hà Nội" },
    { code: "KCC", name: "Trường Đại học Kỹ Thuật Công Nghệ Cần Thơ" },
    { code: "QHQ", name: "Trường Quốc Tế - ĐHQG Hà Nội" },
    { code: "KCN", name: "Trường Đại Học Khoa Học Và Công Nghệ Hà Nội" },
    { code: "DCV", name: "Trường Đại học Công nghiệp Vinh" },
    { code: "DVT", name: "Trường Đại Học Trà Vinh" },
    { code: "NLS", name: "Trường Đại Học Nông Lâm TPHCM" },
    { code: "HVC", name: "Học viện cán bộ TPHCM" },
    { code: "XDA", name: "Trường Đại Học Xây Dựng Hà Nội" },
    { code: "SKH", name: "Trường Đại Học Sư Phạm Kỹ Thuật Hưng Yên" },
    { code: "MBS", name: "Trường Đại Học Mở TPHCM" },
    { code: "FBU", name: "Trường Đại Học Tài Chính Ngân Hàng Hà Nội" },
    { code: "GTA", name: "Trường Đại học Công nghệ Giao thông vận tải" },
    { code: "MDA", name: "Trường Đại Học Mỏ Địa Chất" },
    { code: "DDL", name: "Trường Đại Học Điện Lực" },
    { code: "TDS", name: "Trường Đại Học Thể Dục Thể Thao TPHCM" },
    { code: "DPD", name: "Trường Đại Học Phương Đông" },
    { code: "VLU", name: "Trường Đại Học Sư Phạm Kỹ Thuật Vĩnh Long" },
    { code: "KTD", name: "Trường Đại Học Kiến Trúc Đà Nẵng" },
    { code: "DQK", name: "Trường Đại Học Kinh Doanh và Công Nghệ Hà Nội" },
    { code: "DTK", name: "Trường Đại Học Kỹ Thuật Công Nghiệp Thái Nguyên" },
    { code: "STS", name: "Trường Đại Học Sư Phạm Thể Dục Thể Thao TPHCM" },
    { code: "UKH", name: "Trường Đại học Khánh Hòa" },
    { code: "DSK", name: "Trường Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng" },
    { code: "NHB", name: "Học Viện Ngân Hàng (Phân Viện Bắc Ninh)" },
    { code: "DHI", name: "Khoa Quốc tế - Đại học Huế" },
    { code: "CMC", name: "Trường Đại Học CMC" },
    { code: "NTT", name: "Trường Đại Học Nguyễn Tất Thành" },
    { code: "DHK", name: "Trường Đại Học Kinh Tế - Đại Học Huế" },
    { code: "DHD", name: "Trường Du Lịch - Đại Học Huế" },
    { code: "KGH", name: "Trường Sĩ Quan Không Quân - Hệ Đại học" },
    { code: "DTC", name: "Trường Đại học Công Nghệ Thông Tin và Truyền Thông Thái Nguyên" },
    { code: "HGH", name: "Trường Sĩ Quan Phòng Hóa" },
    { code: "TGH", name: "Trường Sĩ Quan Tăng - Thiết Giáp" },
    { code: "HVQ", name: "Học Viện Quản Lý Giáo Dục" },
    { code: "DDT", name: "Đại Học Duy Tân" },
    { code: "DNC", name: "Trường Đại học Nam Cần Thơ" },
    { code: "HIU", name: "Trường Đại Học Quốc Tế Hồng Bàng" },
    { code: "TTU", name: "Trường Đại học Tân Tạo" },
    { code: "TTD", name: "Trường Đại Học Thể Dục Thể Thao Đà Nẵng" },
    { code: "DCL", name: "Trường Đại Học Cửu Long" },
    { code: "DVL", name: "Trường Đại Học Văn Lang" },
    { code: "DPC", name: "Trường Đại Học Phan Châu Trinh" },
    { code: "UKB", name: "Trường Đại Học Kinh Bắc" },
    { code: "ETU", name: "Trường Đại Học Hòa Bình" },
    { code: "DDN", name: "Trường Đại Học Đại Nam" },
    { code: "VTT", name: "Trường Đại Học Võ Trường Toản" },
    { code: "DAD", name: "Trường Đại Học Đông Á" },
    { code: "SNH", name: "Trường Sĩ Quan Công Binh - Hệ Quân sự - Đại học Ngô Quyền" },
    { code: "DCH", name: "Trường Sĩ Quan Đặc Công" },
    { code: "HCB", name: "Trường Đại Học Kỹ Thuật - Hậu Cần Công An Nhân Dân (Phía Bắc)" },
    { code: "HCN", name: "Trường Đại Học Kỹ Thuật - Hậu Cần Công An Nhân Dân (Phía Nam)" },
    { code: "PBH", name: "Trường Sĩ Quan Pháo Binh" },
    { code: "KSV", name: "Đại học Kinh Tế TPHCM - Phân hiệu Vĩnh Long" },
    { code: "QHD", name: "Trường Quản Trị và Kinh Doanh - ĐHQG Hà Nội" },
    { code: "VGU", name: "Trường Đại Học Việt Đức" },
    { code: "TLS", name: "Trường Đại Học Thủy Lợi (Cơ sở 2)" },
    { code: "SDU", name: "Trường Đại học Sao Đỏ" },
    { code: "PCS", name: "Trường Đại Học Phòng Cháy Chữa Cháy (phía Nam)" },
    { code: "PCH", name: "Trường Đại Học Phòng Cháy Chữa Cháy (Phía Bắc)" },
    { code: "NLN", name: "Phân hiệu Đại học Nông Lâm TPHCM tại Ninh Thuận" },
    { code: "DTD", name: "Trường Đại Học Tây Đô" },
    { code: "DKC", name: "Trường Đại học Công Nghệ TPHCM" },
    { code: "DDU", name: "Trường Đại Học Đông Đô" },
    { code: "DLH", name: "Trường Đại Học Lạc Hồng" },
    { code: "DDB", name: "Trường Đại Học Thành Đông" },
    { code: "DHA", name: "Trường Đại học Luật Huế" },
    { code: "DYD", name: "Trường Đại Học Yersin Đà Lạt" },
    { code: "TDD", name: "Trường Đại học Thành Đô" },
    { code: "DBD", name: "Trường Đại Học Bình Dương" },
    { code: "DTV", name: "Trường Đại Học Lương Thế Vinh" },
    { code: "VJU", name: "Trường Đại học Việt Nhật - ĐHQG Hà Nội" },
    { code: "BVU", name: "Trường Đại Học Bà Rịa – Vũng Tàu" },
    { code: "DHN", name: "Trường Đại Học Nghệ Thuật Huế" },
    { code: "MIT", name: "Trường Đại học Công nghệ Miền Đông" },
    { code: "FPT", name: "Trường Đại Học FPT" },
    { code: "DKB", name: "Trường Đại Học Kinh Tế Kỹ Thuật Bình Dương" },
    { code: "UEF", name: "Trường Đại Học Kinh Tế Tài Chính TPHCM" },
    { code: "DFA", name: "Trường Đại học Tài chính Quản trị kinh doanh" },
    { code: "TTG", name: "Trường Đại Học Tiền Giang" },
    { code: "DTE", name: "Trường Đại học Kinh tế Quản trị kinh doanh Thái Nguyên" },
    { code: "PVU", name: "Trường Đại Học Dầu Khí Việt Nam" },
    { code: "DNT", name: "Trường Đại Học Ngoại Ngữ Tin Học TPHCM" },
    { code: "SKV", name: "Trường Đại Học Sư Phạm Kỹ Thuật Vinh" },
    { code: "CEA", name: "Trường Đại học Kinh Tế Nghệ An" },
    { code: "LNH", name: "Trường Đại Học Lâm nghiệp" },
    { code: "DVH", name: "Trường Đại Học Văn Hiến" },
    { code: "DQT", name: "Trường Đại Học Quang Trung" },
    { code: "HSU", name: "Trường Đại Học Hoa Sen" },
    { code: "DPT", name: "Trường Đại Học Phan Thiết" },
    { code: "DVP", name: "Trường Đại Học Trưng Vương" },
    { code: "YDD", name: "Trường Đại Học Điều Dưỡng Nam Định" },
    { code: "THU", name: "Trường Đại học Y khoa Tokyo Việt Nam" },
    { code: "DCD", name: "Trường Đại Học Công Nghệ Đồng Nai" },
    { code: "EIU", name: "Trường Đại Học Quốc Tế Miền Đông" },
    { code: "DDV", name: "Viện nghiên cứu và đào tạo Việt Anh - Đại học Đà Nẵng" },
    { code: "TDB", name: "Trường Đại Học Thể Dục Thể Thao Bắc Ninh" },
    { code: "DHE", name: "Khoa Kỹ thuật và Công nghệ - Đại học Huế" },
    { code: "DTB", name: "Trường Đại Học Thái Bình" },
    { code: "HVD", name: "Học Viện Dân Tộc" },
    { code: "DHT", name: "Trường Đại Học Khoa Học Huế" },
    { code: "DTZ", name: "Trường Đại Học Khoa Học Thái Nguyên" },
    { code: "HDT", name: "Trường Đại Học Hồng Đức" },
    { code: "DNU", name: "Trường Đại Học Đồng Nai" },
    { code: "LNS", name: "Phân hiệu Đại Học Lâm nghiệp tại Đồng Nai" },
    { code: "DTM", name: "Trường Đại học Tài Nguyên và Môi Trường TPHCM" },
    { code: "NTU", name: "Trường Đại Học Nguyễn Trãi" },
    { code: "CCM", name: "Trường Đại Học Công Nghiệp Dệt May Hà Nội" },
    { code: "VUI", name: "Trường Đại Học Công Nghiệp Việt Trì" },
    { code: "QSP", name: "Phân hiệu Đại học Quốc gia TPHCM tại Bến Tre" },
    { code: "DHL", name: "Trường Đại Học Nông Lâm Huế" },
    { code: "DTQ", name: "Khoa Quốc Tế - Đại Học Thái Nguyên" },
    { code: "SIU", name: "Trường Đại Học Quốc Tế Sài Gòn" },
    { code: "DCA", name: "Trường Đại Học Chu Văn An" },
    { code: "DLA", name: "Trường Đại Học Kinh Tế Công Nghiệp Long An" },
    { code: "DBH", name: "Trường Đại Học Quốc Tế Bắc Hà" },
    { code: "SKN", name: "Trường Đại Học Sư Phạm Kỹ Thuật Nam Định" },
    { code: "NLG", name: "Phân hiệu Đại học Nông Lâm TPHCM tại Gia Lai" },
    { code: "DTN", name: "Trường Đại Học Nông Lâm Thái Nguyên" },
    { code: "UMT", name: "Trường Đại học Quản lý và công nghệ TPHCM" },
    { code: "DCQ", name: "Trường Đại Học Công Nghệ và Quản Lý Hữu Nghị" },
    { code: "DHQ", name: "Phân Hiệu Đại Học Huế tại Quảng Trị" },
    { code: "TBD", name: "Trường Đại Học Thái Bình Dương" },
    { code: "DHV", name: "Trường Đại học Hùng Vương TPHCM" },
    { code: "DVB", name: "Trường Đại học Kinh tế công nghệ Thái Nguyên" },
    { code: "DPX", name: "Trường Đại Học Phú Xuân" },
    { code: "HPU", name: "Trường Đại học Quản lý và Công nghệ Hải Phòng" },
    { code: "MTU", name: "Trường Đại Học Xây Dựng Miền Tây" },
    { code: "VHD", name: "Trường Đại Học Công Nghiệp Việt - Hung" },
    { code: "LNA", name: "Phân hiệu Đại học Lâm nghiệp tỉnh Gia Lai" },
    { code: "NHP", name: "Học Viện Ngân Hàng (Phân Viện Phú Yên)" },
    { code: "UFA", name: "Trường Đại học Tài Chính Kế Toán" },
    { code: "GDU", name: "Trường Đại Học Gia Định" },
    { code: "DDM", name: "Trường Đại Học Công Nghiệp Quảng Ninh" },
    { code: "XDT", name: "Trường Đại Học Xây Dựng Miền Trung" },
    { code: "DSG", name: "Trường Đại Học Công Nghệ Sài Gòn" },
    { code: "XDN", name: "Phân hiệu Đại học Xây dựng miền Trung tại Đà Nẵng" },
    { code: "DBG", name: "Trường Đại học Nông Lâm Bắc Giang" },
    { code: "TTB", name: "Trường Đại Học Tây Bắc" },
    { code: "TDL", name: "Trường Đại Học Đà Lạt" },
    { code: "DTP", name: "Phân Hiệu Đại Học Thái Nguyên Tại Lào Cai" },
    { code: "TQU", name: "Trường Đại học Tân Trào" },
    { code: "TKG", name: "Trường Đại học Kiên Giang" },
    { code: "DVD", name: "Trường Đại Học Văn Hóa, Thể Thao Và Du Lịch Thanh Hóa" },
    { code: "DTG", name: "Phân hiệu Đại học Thái Nguyên tại Hà Giang" },
    { code: "DNB", name: "Trường Đại Học Hoa Lư" },
    { code: "LBS", name: "Trường Đại học Nguyễn Huệ" },
    { code: "HVA", name: "Học Viện Âm Nhạc Huế" },
    { code: "NVH", name: "Học Viện Âm Nhạc Quốc Gia Việt Nam" },
    { code: "NVS", name: "Nhạc Viện TPHCM" },
    { code: "DVX", name: "Trường Đại Học Công Nghệ Vạn Xuân" },
    { code: "DHH", name: "Trường Đại Học Hà Hoa Tiên" },
    { code: "MTC", name: "Trường Đại Học Mỹ Thuật Công Nghiệp" },
    { code: "MTS", name: "Trường Đại Học Mỹ Thuật TPHCM" },
    { code: "MTH", name: "Trường Đại Học Mỹ Thuật Việt Nam" },
    { code: "YHT", name: "Phân hiệu Đại học Y Hà Nội tại Thanh Hóa" },
    { code: "RMU", name: "Trường Đại Học Quốc Tế RMIT Việt Nam" },
    { code: "RHM", name: "Trường Đại Học Răng – Hàm – Mặt" },
    { code: "SKD", name: "Trường Đại Học Sân Khấu Điện Ảnh Hà Nội" },
    { code: "CIV", name: "Học viện Công giáo Việt Nam" },
    { code: "ZNH", name: "Trường Đại học Văn hóa Nghệ thuật Quân đội" },
    { code: "LCDF", name: "Học viện Thiết kế và Thời trang London Hà Nội" },
    { code: "DNV", name: "Trường Đại học Nội vụ Hà Nội" },
    { code: "VPH", name: "Trường Sĩ Quan Kĩ Thuật Quân Sự - Hệ Quân sự - Đại Học Trần Đại Nghĩa" },
    { code: "DSD", name: "Trường Đại Học Sân Khấu Điện Ảnh TPHCM" },
    { code: "DDA", name: "Trường Đại Học Công Nghệ Đông Á" },
    { code: "BUV", name: "Trường Đại Học Anh Quốc Việt Nam" },
    { code: "BMU", name: "Trường Đại học Y Dược Buôn Ma Thuột" },
    { code: "DDG", name: "Khoa Giáo dục thể chất Đà Nẵng" },
];


// Chọn ra một vài trường nổi bật để hiển thị logo cho người dùng click nhanh
export const featuredUniversities = universityList.filter(u => 
    ['BKA', 'KHA', 'NTH', 'QSB', 'YHB', 'FPT', 'QSC', 'KSA'].includes(u.code)
);
