package com.fpt.edu_trial.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum UniversityCode {
    KHA("Đại Học Kinh Tế Quốc Dân"),
    BKA("Đại Học Bách Khoa Hà Nội"),
    HTC("Học Viện Tài chính"),
    NHH("Học Viện Ngân Hàng"),
    NTH("Trường Đại học Ngoại thương"),
    QSB("Trường Đại Học Bách Khoa HCM"),
    YHB("Trường Đại Học Y Hà Nội"),
    BVH("Học Viện Công Nghệ Bưu Chính Viễn Thông"),
    SPH("Trường Đại Học Sư Phạm Hà Nội"),
    TMU("Trường Đại Học Thương Mại"),
    SPS("Trường Đại Học Sư Phạm TPHCM"),
    YDS("Đại Học Y Dược TPHCM"),
    QHI("Trường Đại Học Công Nghệ – Đại Học Quốc Gia Hà Nội"),
    HNM("Trường Đại học Thủ Đô Hà Nội"),
    GHA("Trường Đại Học Giao Thông Vận Tải"),
    YTB("Trường Đại Học Y Dược Thái Bình"),
    KMA("Học Viện Kỹ Thuật Mật Mã"),
    DCN("Trường Đại Học Công Nghiệp Hà Nội"),
    YPB("Trường Đại Học Y Dược Hải Phòng"),
    IUH("Trường Đại Học Công Nghiệp TPHCM"),
    HPN("Học Viện Phụ Nữ Việt Nam"),
    DKH("Trường Đại Học Dược Hà Nội"),
    ANH("Học Viện An Ninh Nhân Dân"),
    DKY("Trường Đại Học Kỹ Thuật Y Tế Hải Dương"),
    GTS("Trường Đại Học Giao Thông Vận Tải TPHCM"),
    HYD("Học Viện Y Dược Học Cổ Truyền Việt Nam"),
    CSH("Học Viện Cảnh Sát Nhân Dân"),
    DKK("Trường Đại Học Kinh Tế Kỹ Thuật Công Nghiệp"),
    DCT("Trường Đại Học Công Thương TPHCM"),
    LAH("Trường Sĩ Quan Lục Quân 1 - Đại học Trần Quốc Tuấn"),
    HQH("Học Viện Hải Quân"),
    HHK("Học Viện Hàng không Việt Nam"),
    PKA("Trường Đại Học Phenikaa"),
    PKH("Học Viện Phòng Không – Không Quân"),
    CSS("Trường Đại Học Cảnh Sát Nhân Dân"),
    TTH("Trường Sĩ Quan Thông Tin - Hệ Quân sự - Đại Học Thông Tin Liên Lạc"),
    NHF("Trường Đại Học Hà Nội"),
    KQH("Học Viện Kỹ Thuật Quân Sự - Hệ Quân sự"),
    YTC("Trường Đại Học Y Tế Công Cộng"),
    HQT("Học Viện Ngoại Giao"),
    ANS("Trường Đại Học An Ninh Nhân Dân"),
    YCT("Trường Đại Học Y Dược Cần Thơ"),
    TDM("Trường Đại học Thủ Dầu Một"),
    TYS("Trường Đại Học Y Khoa Phạm Ngọc Thạch"),
    DTL("Trường Đại Học Thăng Long"),
    TLA("Trường Đại Học Thủy Lợi"),
    QST("Trường Đại Học Khoa Học Tự Nhiên TPHCM"),
    VHH("Trường Đại Học Văn Hóa Hà Nội"),
    DTT("Trường Đại Học Tôn Đức Thắng"),
    HVN("Học Viện Nông Nghiệp Việt Nam"),
    QHX("Trường Đại Học Khoa Học Xã Hội và Nhân Văn Hà Nội"),
    LPH("Trường Đại Học Luật Hà Nội"),
    QHF("Trường Đại Học Ngoại Ngữ - ĐH Quốc gia Hà Nội"),
    HBT("Học viện Báo chí và Tuyên truyền"),
    QHT("Trường Đại Học Khoa Học Tự Nhiên Hà Nội"),
    QHE("Trường Đại Học Kinh Tế - ĐHQG Hà Nội"),
    QSX("Trường Đại Học Khoa Học Xã Hội và Nhân Văn TPHCM"),
    DTS("Đại Học Sư Phạm Thái Nguyên"),
    LCH("Trường Sĩ Quan Chính Trị - Đại Học Chính Trị"),
    TCT("Trường Đại Học Cần Thơ"),
    DKS("Trường Đại học Kiểm Sát Hà Nội"),
    BPH("Học Viện Biên Phòng"),
    QHL("Trường Đại học Luật – ĐHQG Hà Nội"),
    DHS("Trường Đại Học Sư Phạm Huế"),
    QSC("Trường Đại Học Công Nghệ Thông Tin - ĐHQG TPHCM"),
    SGD("Trường Đại Học Sài Gòn"),
    NQH("Học Viện Khoa Học Quân Sự - Hệ Quân sự"),
    NTS("Trường Đại học Ngoại thương (Cơ sở II)"),
    HTA("Học viện Tòa án"),
    DDS("Trường Đại Học Sư Phạm - Đại Học Đà Nẵng"),
    SP2("Trường Đại Học Sư Phạm Hà Nội 2"),
    QHS("Trường Đại Học Giáo Dục - ĐHQG Hà Nội"),
    VHS("Trường Đại Học Văn Hóa TPHCM"),
    SPK("Trường Đại Học Sư Phạm Kỹ Thuật TPHCM"),
    HTN("Học Viện Thanh Thiếu Niên Việt Nam"),
    YQH("Học Viện Quân Y - Hệ Quân sự"),
    QSK("Trường Đại học Kinh Tế Luật TPHCM"),
    HEH("Học Viện Hậu Cần - Hệ Quân sự"),
    LPS("Trường Đại Học Luật TPHCM"),
    DDF("Trường Đại Học Ngoại Ngữ Đà Nẵng"),
    KSA("Đại Học Kinh Tế TPHCM"),
    QHY("Trường Đại học Y Dược - ĐHQG Hà Nội"),
    DDK("Trường Đại Học Bách Khoa Đà Nẵng"),
    DHF("Trường Đại Học Ngoại Ngữ Huế"),
    DMS("Trường Đại Học Tài Chính Marketing"),
    GSA("Trường Đại Học Giao Thông Vận Tải (Cơ sở 2)"),
    TSN("Trường Đại Học Nha Trang"),
    LBH("Trường Sĩ Quan Lục Quân 2 - Đại học Nguyễn Huệ"),
    BVS("Học Viện Công Nghệ Bưu Chính Viễn Thông (Cơ sở TP.HCM)"),
    YKV("Trường Đại Học Y Khoa Vinh"),
    YDN("Trường Đại học Kỹ thuật Y Dược Đà Nẵng"),
    DTY("Trường Đại Học Y Dược Thái Nguyên"),
    DHY("Trường Đại Học Y Dược Huế"),
    DDY("Trường Y Dược Đà Nẵng"),
    KTS("Trường Đại Học Kiến Trúc TPHCM"),
    HCA("Học Viện Chính Trị Công An Nhân Dân"),
    QSY("Trường Đại học Khoa học sức khỏe TPHCM"),
    QSQ("Trường Đại Học Quốc Tế - ĐHQG TPHCM"),
    THV("Trường Đại Học Hùng Vương"),
    THP("Trường Đại Học Hải Phòng"),
    HCP("Học Viện Chính Sách và Phát Triển"),
    MHN("Trường Đại Học Mở Hà Nội"),
    LDA("Trường Đại Học Công Đoàn"),
    HHA("Trường Đại Học Hàng Hải Việt Nam"),
    KTA("Trường Đại Học Kiến Trúc Hà Nội"),
    TDV("Trường Đại Học Vinh"),
    QSA("Trường Đại Học An Giang"),
    HCH("Học Viện Hành Chính và Quản trị công"),
    SPD("Trường Đại Học Đồng Tháp"),
    QHK("Trường Khoa học liên ngành và Nghệ thuật Hà Nội"),
    TTN("Trường Đại Học Tây Nguyên"),
    DQN("Trường Đại Học Quy Nhơn"),
    DHC("Khoa Giáo Dục Thể Chất Huế"),
    GNT("Trường Đại Học Sư Phạm Nghệ Thuật Trung Ương"),
    DDQ("Trường Đại Học Kinh Tế – Đại Học Đà Nẵng"),
    VKU("Trường Đại học Công nghệ Thông tin và Truyền thông Việt Hàn - Đại học Đà Nẵng"),
    DTF("Trường Ngoại Ngữ Thái Nguyên"),
    HLU("Trường Đại Học Hạ Long"),
    DKT("Trường Đại Học Hải Dương"),
    DQB("Trường Đại Học Quảng Bình"),
    DPQ("Trường Đại Học Phạm Văn Đồng"),
    HHT("Trường Đại Học Hà Tĩnh"),
    DMT("Trường Đại học Tài Nguyên và Môi Trường Hà Nội"),
    HCS("Học Viện Hành Chính Và Quản Trị Công (phía Nam)"),
    NHS("Trường Đại Học Ngân Hàng TPHCM"),
    DLX("Trường Đại Học Lao Động – Xã Hội"),
    DBL("Trường Đại Học Bạc Liêu"),
    DQU("Trường Đại Học Quảng Nam"),
    DLS("Trường Đại Học Lao Động – Xã Hội (Cơ sở II)"),
    DPY("Trường Đại Học Phú Yên"),
    DDP("Phân Hiệu Đại Học Đà Nẵng tại Kon Tum"),
    TDH("Trường Đại Học Sư Phạm Thể Dục Thể Thao Hà Nội"),
    KCC("Trường Đại học Kỹ Thuật Công Nghệ Cần Thơ"),
    QHQ("Trường Quốc Tế - ĐHQG Hà Nội"),
    KCN("Trường Đại Học Khoa Học Và Công Nghệ Hà Nội"),
    DCV("Trường Đại học Công nghiệp Vinh"),
    DVT("Trường Đại Học Trà Vinh"),
    NLS("Trường Đại Học Nông Lâm TPHCM"),
    HVC("Học viện cán bộ TPHCM"),
    XDA("Trường Đại Học Xây Dựng Hà Nội"),
    SKH("Trường Đại Học Sư Phạm Kỹ Thuật Hưng Yên"),
    MBS("Trường Đại Học Mở TPHCM"),
    FBU("Trường Đại Học Tài Chính Ngân Hàng Hà Nội"),
    GTA("Trường Đại học Công nghệ Giao thông vận tải"),
    MDA("Trường Đại Học Mỏ Địa Chất"),
    DDL("Trường Đại Học Điện Lực"),
    TDS("Trường Đại Học Thể Dục Thể Thao TPHCM"),
    DPD("Trường Đại Học Phương Đông"),
    VLU("Trường Đại Học Sư Phạm Kỹ Thuật Vĩnh Long"),
    KTD("Trường Đại Học Kiến Trúc Đà Nẵng"),
    DQK("Trường Đại Học Kinh Doanh và Công Nghệ Hà Nội"),
    DTK("Trường Đại Học Kỹ Thuật Công Nghiệp Thái Nguyên"),
    STS("Trường Đại Học Sư Phạm Thể Dục Thể Thao TPHCM"),
    UKH("Trường Đại học Khánh Hòa"),
    DSK("Trường Đại học Sư phạm Kỹ thuật - Đại học Đà Nẵng"),
    NHB("Học Viện Ngân Hàng (Phân Viện Bắc Ninh)"),
    DHI("Khoa Quốc tế - Đại học Huế"),
    CMC("Trường Đại Học CMC"),
    NTT("Trường Đại Học Nguyễn Tất Thành"),
    DHK("Trường Đại Học Kinh Tế - Đại Học Huế"),
    DHD("Trường Du Lịch - Đại Học Huế"),
    KGH("Trường Sĩ Quan Không Quân - Hệ Đại học"),
    DTC("Trường Đại học Công Nghệ Thông Tin và Truyền Thông Thái Nguyên"),
    HGH("Trường Sĩ Quan Phòng Hóa"),
    TGH("Trường Sĩ Quan Tăng - Thiết Giáp"),
    HVQ("Học Viện Quản Lý Giáo Dục"),
    DDT("Đại Học Duy Tân"),
    DNC("Trường Đại học Nam Cần Thơ"),
    HIU("Trường Đại Học Quốc Tế Hồng Bàng"),
    TTU("Trường Đại học Tân Tạo"),
    TTD("Trường Đại Học Thể Dục Thể Thao Đà Nẵng"),
    DCL("Trường Đại Học Cửu Long"),
    DVL("Trường Đại Học Văn Lang"),
    DPC("Trường Đại Học Phan Châu Trinh"),
    UKB("Trường Đại Học Kinh Bắc"),
    ETU("Trường Đại Học Hòa Bình"),
    DDN("Trường Đại Học Đại Nam"),
    VTT("Trường Đại Học Võ Trường Toản"),
    DAD("Trường Đại Học Đông Á"),
    SNH("Trường Sĩ Quan Công Binh - Hệ Quân sự - Đại học Ngô Quyền"),
    DCH("Trường Sĩ Quan Đặc Công"),
    HCB("Trường Đại Học Kỹ Thuật - Hậu Cần Công An Nhân Dân (Phía Bắc)"),
    HCN("Trường Đại Học Kỹ Thuật - Hậu Cần Công An Nhân Dân (Phía Nam)"),
    PBH("Trường Sĩ Quan Pháo Binh"),
    KSV("Đại học Kinh Tế TPHCM - Phân hiệu Vĩnh Long"),
    QHD("Trường Quản Trị và Kinh Doanh - ĐHQG Hà Nội"),
    VGU("Trường Đại Học Việt Đức"),
    TLS("Trường Đại Học Thủy Lợi (Cơ sở 2)"),
    SDU("Trường Đại học Sao Đỏ"),
    PCS("Trường Đại Học Phòng Cháy Chữa Cháy (phía Nam)"),
    PCH("Trường Đại Học Phòng Cháy Chữa Cháy (Phía Bắc)"),
    NLN("Phân hiệu Đại học Nông Lâm TPHCM tại Ninh Thuận"),
    DTD("Trường Đại Học Tây Đô"),
    DKC("Trường Đại học Công Nghệ TPHCM"),
    DDU("Trường Đại Học Đông Đô"),
    DLH("Trường Đại Học Lạc Hồng"),
    DDB("Trường Đại Học Thành Đông"),
    DHA("Trường Đại học Luật Huế"),
    DYD("Trường Đại Học Yersin Đà Lạt"),
    TDD("Trường Đại học Thành Đô"),
    DBD("Trường Đại Học Bình Dương"),
    DTV("Trường Đại Học Lương Thế Vinh"),
    VJU("Trường Đại học Việt Nhật - ĐHQG Hà Nội"),
    BVU("Trường Đại Học Bà Rịa – Vũng Tàu"),
    DHN("Trường Đại Học Nghệ Thuật Huế"),
    MIT("Trường Đại học Công nghệ Miền Đông"),
    FPT("Trường Đại Học FPT"),
    DKB("Trường Đại Học Kinh Tế Kỹ Thuật Bình Dương"),
    UEF("Trường Đại Học Kinh Tế Tài Chính TPHCM"),
    DFA("Trường Đại học Tài chính Quản trị kinh doanh"),
    TTG("Trường Đại Học Tiền Giang"),
    DTE("Trường Đại học Kinh tế Quản trị kinh doanh Thái Nguyên"),
    PVU("Trường Đại Học Dầu Khí Việt Nam"),
    DNT("Trường Đại Học Ngoại Ngữ Tin Học TPHCM"),
    SKV("Trường Đại Học Sư Phạm Kỹ Thuật Vinh"),
    CEA("Trường Đại học Kinh Tế Nghệ An"),
    LNH("Trường Đại Học Lâm nghiệp"),
    DVH("Trường Đại Học Văn Hiến"),
    DQT("Trường Đại Học Quang Trung"),
    HSU("Trường Đại Học Hoa Sen"),
    DPT("Trường Đại Học Phan Thiết"),
    DVP("Trường Đại Học Trưng Vương"),
    YDD("Trường Đại Học Điều Dưỡng Nam Định"),
    THU("Trường Đại học Y khoa Tokyo Việt Nam"),
    DCD("Trường Đại Học Công Nghệ Đồng Nai"),
    EIU("Trường Đại Học Quốc Tế Miền Đông"),
    DDV("Viện nghiên cứu và đào tạo Việt Anh - Đại học Đà Nẵng"),
    TDB("Trường Đại Học Thể Dục Thể Thao Bắc Ninh"),
    DHE("Khoa Kỹ thuật và Công nghệ - Đại học Huế"),
    DTB("Trường Đại Học Thái Bình"),
    HVD("Học Viện Dân Tộc"),
    DHT("Trường Đại Học Khoa Học Huế"),
    DTZ("Trường Đại Học Khoa Học Thái Nguyên"),
    HDT("Trường Đại Học Hồng Đức"),
    DNU("Trường Đại Học Đồng Nai"),
    LNS("Phân hiệu Đại Học Lâm nghiệp tại Đồng Nai"),
    DTM("Trường Đại học Tài Nguyên và Môi Trường TPHCM"),
    NTU("Trường Đại Học Nguyễn Trãi"),
    CCM("Trường Đại Học Công Nghiệp Dệt May Hà Nội"),
    VUI("Trường Đại Học Công Nghiệp Việt Trì"),
    QSP("Phân hiệu Đại học Quốc gia TPHCM tại Bến Tre"),
    DHL("Trường Đại Học Nông Lâm Huế"),
    DTQ("Khoa Quốc Tế - Đại Học Thái Nguyên"),
    SIU("Trường Đại Học Quốc Tế Sài Gòn"),
    DCA("Trường Đại Học Chu Văn An"),
    DLA("Trường Đại Học Kinh Tế Công Nghiệp Long An"),
    DBH("Trường Đại Học Quốc Tế Bắc Hà"),
    SKN("Trường Đại Học Sư Phạm Kỹ Thuật Nam Định"),
    NLG("Phân hiệu Đại học Nông Lâm TPHCM tại Gia Lai"),
    DTN("Trường Đại Học Nông Lâm Thái Nguyên"),
    UMT("Trường Đại học Quản lý và công nghệ TPHCM"),
    DCQ("Trường Đại Học Công Nghệ và Quản Lý Hữu Nghị"),
    DHQ("Phân Hiệu Đại Học Huế tại Quảng Trị"),
    TBD("Trường Đại Học Thái Bình Dương"),
    DHV("Trường Đại học Hùng Vương TPHCM"),
    DVB("Trường Đại học Kinh tế công nghệ Thái Nguyên"),
    DPX("Trường Đại Học Phú Xuân"),
    HPU("Trường Đại học Quản lý và Công nghệ Hải Phòng"),
    MTU("Trường Đại Học Xây Dựng Miền Tây"),
    VHD("Trường Đại Học Công Nghiệp Việt - Hung"),
    LNA("Phân hiệu Đại học Lâm nghiệp tỉnh Gia Lai"),
    NHP("Học Viện Ngân Hàng (Phân Viện Phú Yên)"),
    UFA("Trường Đại học Tài Chính Kế Toán"),
    GDU("Trường Đại Học Gia Định"),
    DDM("Trường Đại Học Công Nghiệp Quảng Ninh"),
    XDT("Trường Đại Học Xây Dựng Miền Trung"),
    DSG("Trường Đại Học Công Nghệ Sài Gòn"),
    XDN("Phân hiệu Đại học Xây dựng miền Trung tại Đà Nẵng"),
    DBG("Trường Đại học Nông Lâm Bắc Giang"),
    TTB("Trường Đại Học Tây Bắc"),
    TDL("Trường Đại Học Đà Lạt"),
    DTP("Phân Hiệu Đại Học Thái Nguyên Tại Lào Cai"),
    TQU("Trường Đại học Tân Trào"),
    TKG("Trường Đại học Kiên Giang"),
    DVD("Trường Đại Học Văn Hóa, Thể Thao Và Du Lịch Thanh Hóa"),
    DTG("Phân hiệu Đại học Thái Nguyên tại Hà Giang"),
    DNB("Trường Đại Học Hoa Lư"),
    LBS("Trường Đại học Nguyễn Huệ"),
    HVA("Học Viện Âm Nhạc Huế"),
    NVH("Học Viện Âm Nhạc Quốc Gia Việt Nam"),
    NVS("Nhạc Viện TPHCM"),
    DVX("Trường Đại Học Công Nghệ Vạn Xuân"),
    DHH("Trường Đại Học Hà Hoa Tiên"),
    MTC("Trường Đại Học Mỹ Thuật Công Nghiệp"),
    MTS("Trường Đại Học Mỹ Thuật TPHCM"),
    MTH("Trường Đại Học Mỹ Thuật Việt Nam"),
    YHT("Phân hiệu Đại học Y Hà Nội tại Thanh Hóa"),
    RMU("Trường Đại Học Quốc Tế RMIT Việt Nam"),
    RHM("Trường Đại Học Răng – Hàm – Mặt"),
    SKD("Trường Đại Học Sân Khấu Điện Ảnh Hà Nội"),
    CIV("Học viện Công giáo Việt Nam"),
    ZNH("Trường Đại học Văn hóa Nghệ thuật Quân đội"),
    LCDF("Học viện Thiết kế và Thời trang London Hà Nội"),
    DNV("Trường Đại học Nội vụ Hà Nội"),
    VPH("Trường Sĩ Quan Kĩ Thuật Quân Sự - Hệ Quân sự - Đại Học Trần Đại Nghĩa"),
    DSD("Trường Đại Học Sân Khấu Điện Ảnh TPHCM"),
    DDA("Trường Đại Học Công Nghệ Đông Á"),
    BUV("Trường Đại Học Anh Quốc Việt Nam"),
    BMU("Trường Đại học Y Dược Buôn Ma Thuột"),
    DDG("Khoa Giáo dục thể chất Đà Nẵng");

    private final String universityName;
}